# ============================================================
# Project  : Secured Network Infrastructure & Server Monitoring Lab
# Service  : Apache2 SSL
# File     : default-ssl.conf
# ============================================================

<IfModule mod_ssl.c>
<VirtualHost *:443>

    ServerAdmin pnkht@lab-smk

    ServerName www.lab-smk.xyz
    ServerAlias lab-smk.xyz

    DocumentRoot /var/www/html

    SSLEngine on

    SSLCertificateFile    /etc/apache2/ssl/lab-smk.cert
    SSLCertificateKeyFile /etc/apache2/ssl/lab-smk.key

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
</IfModule>
