# ============================================================
# Project  : Secured Network Infrastructure & Server Monitoring Lab
# Service  : Apache2 SSL
# File     : default-ssl.conf
# ============================================================

<IfModule mod_ssl.c>
<VirtualHost *:443>

    ServerAdmin pnkht@lab

    ServerName www.pnkht-lab.xyz
    ServerAlias pnkht-lab.xyz

    DocumentRoot /var/www/html/pnkht-lab

    SSLEngine on

    SSLCertificateFile    /etc/apache2/ssl/pnkht-lab.cert
    SSLCertificateKeyFile /etc/apache2/ssl/pnkht-lab.key

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
</IfModule>
