# ============================================================
# Project  : Secured Network Infrastructure & Server Monitoring Lab
# Service  : SNMP (Cacti)
# ============================================================

agentaddress 192.168.30.10 

rocommunity public 192.168.30.0/24

sysLocation Pinkhat-Lab
sysContact pnkht@mail.xyz

